#!/bin/bash
set -euo pipefail
MODEL_INDEX=${1:?model index required}
OBJECTIVE=${2:?ce or kd required}
SEED=${3:?seed required}
MODE=${4:-full}
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
OURS_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)
REPO_ROOT=$(cd "${OURS_ROOT}/../.." && pwd)
MODEL_TABLE=${RGCLS_MODEL_TABLE:-${REPO_ROOT}/configs/paper_models.tsv}
WORK=${RGCLS_WORKSPACE_ROOT:?set RGCLS_WORKSPACE_ROOT to the dataset/output workspace}
BIN=${RGCLS_PYTHON_ENV_BIN:?set RGCLS_PYTHON_ENV_BIN to the environment bin directory}
ROOT=${RGCLS_OUTPUT_ROOT:-${REPO_ROOT}/outputs/paper_recovery}
ROW=$(sed -e '/^#/d' -e '/^[[:space:]]*$/d' "${MODEL_TABLE}" | sed -n "$((MODEL_INDEX+1))p")
IFS=$'\t' read -r ID BACKBONE TARGET K STRATEGY INIT_CKPT POLICY ATLAS BASE TEACHER TRAIN_DATA VAL_DATA <<< "${ROW}"
INIT_CKPT=${INIT_CKPT_OVERRIDE:-${INIT_CKPT}}
POLICY=${POLICY_OVERRIDE:-${POLICY}}
test -n "${ID}"; test -s "${INIT_CKPT}"; test -s "${POLICY}"
test -s "${ATLAS}/atlas_state.pt"; test -s "${ATLAS}/final_structure_prior.pt"
test -s "${TRAIN_DATA}"; test -s "${VAL_DATA}"
case "${OBJECTIVE}" in
  ce) DISTILL=ce; LKD=0; TEACHER_FREE=True; TOKENIZER=${BASE}; TEACHER_ARG=${BASE} ;;
  kd) DISTILL=ce_kd; LKD=1; TEACHER_FREE=False; TOKENIZER=${TEACHER}; TEACHER_ARG=${TEACHER}; test -s "${TEACHER}/model.safetensors" ;;
  *) echo "invalid objective=${OBJECTIVE}" >&2; exit 2 ;;
esac
if [ "${BACKBONE}" = llama32_3b ]; then
  STEPS=7500; LR=5e-5; LR_BANK=3e-5; LR_ADAPTER=8e-5; WARMUP=750; BATCH=4; ACCUM=2; EVAL_BATCH=8
else
  STEPS=10000; LR=4e-5; LR_BANK=2.5e-5; LR_ADAPTER=6e-5; WARMUP=1000; BATCH=1; ACCUM=2; EVAL_BATCH=4
fi
MAX_RECORDS=0; VAL_MAX=2048; VAL_EVERY=500; EVAL=True
PREFIX=${OUTPUT_PREFIX:-${ROOT}}
if [ "${MODE}" = smoke ]; then
  STEPS=2; WARMUP=0; MAX_RECORDS=64; VAL_MAX=32; VAL_EVERY=1; EVAL=False
  PREFIX=${OUTPUT_PREFIX:-${ROOT}/smoke}
fi
RUN_ID=${ID}_${OBJECTIVE}_s${SEED}
OUT=${PREFIX}/runs/${RUN_ID}; RES=${PREFIX}/results/runs/${RUN_ID}
mkdir -p "${OUT}" "${RES}"
export PATH="${BIN}:/usr/bin:/bin" PYTHON_BIN=${BIN}/python TORCHRUN_BIN=${BIN}/torchrun PYTHONNOUSERSITE=1
CACHE_ROOT=${RGCLS_CACHE_ROOT:-${REPO_ROOT}/.cache/huggingface}
export HF_HOME=${HF_HOME:-${CACHE_ROOT}} HF_DATASETS_CACHE=${HF_DATASETS_CACHE:-${CACHE_ROOT}/datasets} HF_HUB_CACHE=${HF_HUB_CACHE:-${CACHE_ROOT}/hub} TOKENIZERS_PARALLELISM=false OMP_NUM_THREADS=12
unset PYTHONPATH
export RUN_TAG=${RUN_ID} OUT_ROOT=${OUT} RESULTS_DIR=${RES} WORKSPACE_ROOT=${WORK} PROJECT_ROOT=${OURS_ROOT}
export PIPELINE_PY=${OURS_ROOT}/core/newthesis_pipeline_final_llama.py ORIGINAL_SCRIPT_PATH=${SCRIPT_DIR}/run_try_to_recovery_final_llama.sh
export MODEL_PRESET=${BACKBONE} BASE_MODEL=${BASE} TEACHER_CKPT=${TEACHER_ARG} TEACHER_LOADER=native TEACHER_USE_MERGED=False TOKENIZER_NAME_OR_PATH=${TOKENIZER}
export SOURCE_DATA_PATH=${TRAIN_DATA} DATA_PATH=${TRAIN_DATA} PASS1_VAL_DATA_PATH=${VAL_DATA} DATA_SPLIT_ENABLE=False TEST_DATA_ROOT=${RGCLS_TEST_DATA_ROOT:?set RGCLS_TEST_DATA_ROOT}
export FLAP_ENABLE=False DIRECT_TRAIN_ENABLE=False EXTERNAL_ATLAS_DIR=${ATLAS} SHARING_POLICY_PATH=${POLICY} INIT_SHARED_STUDENT_CKPT=${INIT_CKPT}
export NUM_GPUS=2 DEVICE=cuda BATCH_SIZE=${BATCH} PASS1_GRAD_ACCUM_STEPS=${ACCUM} CUTOFF_LEN=384 MAX_RECORDS=${MAX_RECORDS} MAX_BATCHES=0
export USE_LAYER_SCALAR=${USE_LAYER_SCALAR:-True} ADAPTER_EVERY_LAYER=${ADAPTER_EVERY_LAYER:-False} TRAIN_SHARED_BANK=${TRAIN_SHARED_BANK:-False} PRIVATE_DOWN_RANK=${PRIVATE_DOWN_RANK:-64} PRIVATE_DOWN_ALPHA=${PRIVATE_DOWN_ALPHA:-64} PROTO_SEED_STRATEGY=${STRATEGY} SHARING_PARAMETERIZATION=full_parallel
export STUDENT_GRADIENT_CHECKPOINTING=True TEACHER_GRADIENT_CHECKPOINTING=False TRAINING_PROMPT_MODE=decision_aligned LOSS_SCOPE=decision LOSS_EXCLUDE_EOS=True
export PASS1_DISTILL_MODE=${DISTILL} TEACHER_FREE_CE=${TEACHER_FREE} LAMBDA_CE=1 LAMBDA_KD=${LKD} KD_TEMPERATURE=2 LAMBDA_HIDDEN_MSE=0 LAMBDA_CORE=0
export PASS1_CORE_LAYERS=all CORE_USE_METRIC_WHITENING=False CORE_USE_RELIABILITY_WEIGHTING=False CORE_USE_INFORMATION_WEIGHTING=False
export LAMBDA_GEODESIC_CORE=0 LAMBDA_RELATIONAL_CORE=0 LAMBDA_VARIANCE_CORE=0 LAMBDA_MANIFOLD_CORE=0 LAMBDA_DELTA_MANIFOLD_CORE=0
export GENERIC_REPLAY_DATA_PATH='' GENERIC_REPLAY_INTERVAL=0 LAMBDA_GENERIC_REPLAY=0 ON_POLICY_DATA_PATH='' ON_POLICY_INTERVAL=0
export PASS1_STEPS=${STEPS} PASS1_LR=${LR} PASS1_LR_BANK=${LR_BANK} PASS1_LR_ADAPTER=${LR_ADAPTER} PASS1_WEIGHT_DECAY=0.01
export PASS1_LR_SCHEDULE=warmup_cosine PASS1_LR_WARMUP_STEPS=${WARMUP} PASS1_LR_MIN_RATIO=0.01
export PASS1_VAL_EVERY=${VAL_EVERY} PASS1_VAL_MAX_RECORDS=${VAL_MAX} PASS1_VAL_SELECTION_METRIC=decision_ce PASS1_VAL_MIN_IMPROVEMENT=0.000001 PASS1_VAL_SUBSPACE_VIZ_ENABLE=False
export QUANT_BITS=16 EVAL_ENABLE=${EVAL} EVAL_BATCH_SIZE=${EVAL_BATCH} EVAL_DATASETS='ARC-Challenge ARC-Easy hellaswag openbookqa piqa social_i_qa winogrande'
export EVAL_MODE=logprob EVAL_LENGTH_NORM=none EVAL_TRAJECTORY_ENABLE=False SEED=${SEED}
JOB_BASE=${SLURM_ARRAY_JOB_ID:-${SLURM_JOB_ID}}
TASK_OFFSET=${SLURM_ARRAY_TASK_ID:-0}
export MASTER_ADDR=127.0.0.1 MASTER_PORT=$((20000 + (JOB_BASE % 20000) + TASK_OFFSET * 101))
bash "${SCRIPT_DIR}/run_try_to_recovery_final_llama.sh"
test -s "${OUT}/phase1_5_pass1/shared_student.pt"; test -s "${OUT}/phase4_export/deploy_bundle.pt"
if [ "${MODE}" = full ]; then test "$(find "${RES}" -maxdepth 1 -name 'phase1_5_*.json' -type f | wc -l)" -ge 7; fi
